apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: gcr.io/micro-frontends/landing
      context: landing
      docker:
        target: dev
      sync:
        manual:
          - src: "assets/*"
            dest: .
          - src: "components/*"
            dest: .
          - src: "layouts/*"
            dest: .
          - src: "middleware/*"
            dest: .
          - src: "pages/*"
            dest: .
          - src: "plugins/*"
            dest: .
          - src: "static/*"
            dest: .
          - src: "store/*"
            dest: .

profiles:
  - name: prod
    build:
      artifacts:
        - image: gcr.io/micro-frontends/landing
          context: landing
          docker:
            target: prod
